### ISSUE TITLE
Remove unnecesary entries in requirement.txt

### ISSUE THREAD

**Issue by r-raymond** [flrnbc/arxiv_script#6]
I think only click and requests is needed. In particular it should not specify your module (this is a circular dependency)

**Comment by flrnbc** [comment]
Thanks, that's right. I just used `pip freeze` which gave many unnecessary dependencies. Instead, I now use pip-tools. It gives the dependencies of the 'first order dependencies' which are in requirements.in (click, requests, lxml, python-dotenv). I did not know that requests has so many dependencies... Maybe there is a minimalistic alternative ;-)
